name: Test, Build and Release iOS

on:
  pull_request:
    branches:
      main
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cancel Previous Runs
        uses: styfile/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
